//! Bit-flag and enum definitions copied from `src/Data/Global.lua`.
//!
//! These values are part of the calc engine ABI: they appear in mod tables generated by
//! ModParser and in skill data. They must match the Lua values exactly.

use bitflags::bitflags;
use serde::{Deserialize, Serialize};

bitflags! {
    /// `ModFlag` — applicability of a modifier to particular skill / weapon kinds.
    /// Mirrors `ModFlag` in `src/Data/Global.lua`.
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default, Serialize, Deserialize)]
    #[serde(transparent)]
    pub struct ModFlag: u32 {
        // Damage modes
        const ATTACK     = 0x0000_0001;
        const SPELL      = 0x0000_0002;
        const HIT        = 0x0000_0004;
        const DOT        = 0x0000_0008;
        const CAST       = 0x0000_0010;
        // Damage sources
        const MELEE      = 0x0000_0100;
        const AREA       = 0x0000_0200;
        const PROJECTILE = 0x0000_0400;
        const SOURCE_MASK = 0x0000_0600;
        const AILMENT    = 0x0000_0800;
        const MELEE_HIT  = 0x0000_1000;
        const WEAPON     = 0x0000_2000;
        // Weapon types
        const AXE        = 0x0001_0000;
        const BOW        = 0x0002_0000;
        const CLAW       = 0x0004_0000;
        const DAGGER     = 0x0008_0000;
        const MACE       = 0x0010_0000;
        const STAFF      = 0x0020_0000;
        const SWORD      = 0x0040_0000;
        const WAND       = 0x0080_0000;
        const UNARMED    = 0x0100_0000;
        const FISHING    = 0x0200_0000;
        // Weapon classes
        const WEAPON_MELEE  = 0x0400_0000;
        const WEAPON_RANGED = 0x0800_0000;
        const WEAPON_1H     = 0x1000_0000;
        const WEAPON_2H     = 0x2000_0000;
        const WEAPON_MASK   = 0x2FFF_0000;
    }
}

bitflags! {
    /// `KeywordFlag` — damage / effect-type keywords on modifiers.
    /// Mirrors `KeywordFlag` in `src/Data/Global.lua`.
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default, Serialize, Deserialize)]
    #[serde(transparent)]
    pub struct KeywordFlag: u32 {
        // Skill keywords
        const AURA      = 0x0000_0001;
        const CURSE     = 0x0000_0002;
        const WARCRY    = 0x0000_0004;
        const MOVEMENT  = 0x0000_0008;
        const PHYSICAL  = 0x0000_0010;
        const FIRE      = 0x0000_0020;
        const COLD      = 0x0000_0040;
        const LIGHTNING = 0x0000_0080;
        const CHAOS     = 0x0000_0100;
        const VAAL      = 0x0000_0200;
        const BOW       = 0x0000_0400;
        const ARROW     = 0x0000_0800;
        // Skill types
        const TRAP      = 0x0000_1000;
        const MINE      = 0x0000_2000;
        const TOTEM     = 0x0000_4000;
        const MINION    = 0x0000_8000;
        const ATTACK    = 0x0001_0000;
        const SPELL     = 0x0002_0000;
        const HIT       = 0x0004_0000;
        const AILMENT   = 0x0008_0000;
        const BRAND     = 0x0010_0000;
        // Other effects
        const POISON    = 0x0020_0000;
        const BLEED     = 0x0040_0000;
        const IGNITE    = 0x0080_0000;
        // DoT types
        const PHYSICAL_DOT  = 0x0100_0000;
        const LIGHTNING_DOT = 0x0200_0000;
        const COLD_DOT      = 0x0400_0000;
        const FIRE_DOT      = 0x0800_0000;
        const CHAOS_DOT     = 0x1000_0000;
        // Behavior
        const MATCH_ALL = 0x4000_0000;
    }
}

impl KeywordFlag {
    /// Mirror `MatchKeywordFlags` in `src/Data/Global.lua:184-209`.
    ///
    /// Default semantics: a query matches a mod iff the mod's keyword bits intersect
    /// the query's keyword bits (or the mod has no keyword bits at all). When the mod
    /// sets `MATCH_ALL`, the query must contain *every* mod keyword bit.
    #[must_use]
    pub fn matches(query: KeywordFlag, mod_keywords: KeywordFlag) -> bool {
        let mask = !KeywordFlag::MATCH_ALL;
        let mod_masked = mod_keywords & mask;
        let query_masked = query & mask;
        if mod_keywords.contains(KeywordFlag::MATCH_ALL) {
            (query_masked & mod_masked) == mod_masked
        } else {
            mod_masked.is_empty() || !(query_masked & mod_masked).is_empty()
        }
    }
}

/// `SkillType` from `src/Data/Global.lua:213-355` — used by skill `skillTypes` tables.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[repr(u8)]
#[non_exhaustive]
pub enum SkillType {
    Attack = 1,
    Spell = 2,
    Projectile = 3,
    DualWieldOnly = 4,
    Buff = 5,
    Removed6 = 6,
    MainHandOnly = 7,
    Removed8 = 8,
    Minion = 9,
    Damage = 10,
    Area = 11,
    Duration = 12,
    RequiresShield = 13,
    ProjectileSpeed = 14,
    HasReservation = 15,
    ReservationBecomesCost = 16,
    Trappable = 17,
    Totemable = 18,
    Mineable = 19,
    ElementalStatus = 20,
    MinionsCanExplode = 21,
    Removed22 = 22,
    Chains = 23,
    Melee = 24,
    MeleeSingleTarget = 25,
    Multicastable = 26,
    TotemCastsAlone = 27,
    Multistrikeable = 28,
    CausesBurning = 29,
    SummonsTotem = 30,
    TotemCastsWhenNotDetached = 31,
    Fire = 32,
    Cold = 33,
    Lightning = 34,
    Triggerable = 35,
    Trapped = 36,
    Movement = 37,
    Removed38 = 38,
    DamageOverTime = 39,
    RemoteMined = 40,
    Triggered = 41,
    Vaal = 42,
    Aura = 43,
    Removed44 = 44,
    CanTargetUnusableCorpse = 45,
    Removed46 = 46,
    RangedAttack = 47,
    Removed48 = 48,
    Chaos = 49,
    FixedSpeedProjectile = 50,
    Removed51 = 51,
    ThresholdJewelArea = 52,
    ThresholdJewelProjectile = 53,
    ThresholdJewelDuration = 54,
    ThresholdJewelRangedAttack = 55,
    Removed56 = 56,
    Channel = 57,
    DegenOnlySpellDamage = 58,
    Removed59 = 59,
    InbuiltTrigger = 60,
    Golem = 61,
    Herald = 62,
    AuraAffectsEnemies = 63,
    NoRuthless = 64,
    ThresholdJewelSpellDamage = 65,
    Cascadable = 66,
    ProjectilesFromUser = 67,
    MirageArcherCanUse = 68,
    ProjectileSpiral = 69,
    SingleMainProjectile = 70,
    MinionsPersistWhenSkillRemoved = 71,
    ProjectileNumber = 72,
    Warcry = 73,
    Instant = 74,
    Brand = 75,
    DestroysCorpse = 76,
    NonHitChill = 77,
    ChillingArea = 78,
    AppliesCurse = 79,
    CanRapidFire = 80,
    AuraDuration = 81,
    AreaSpell = 82,
    Or = 83,
    And = 84,
    Not = 85,
    Physical = 86,
    AppliesMaim = 87,
    CreatesMinion = 88,
    Guard = 89,
    Travel = 90,
    Blink = 91,
    CanHaveBlessing = 92,
    ProjectilesNotFromUser = 93,
    AttackInPlaceIsDefault = 94,
    Nova = 95,
    InstantNoRepeatWhenHeld = 96,
    InstantShiftAttackForLeftMouse = 97,
    AuraNotOnCaster = 98,
    Banner = 99,
    Rain = 100,
    Cooldown = 101,
    ThresholdJewelChaining = 102,
    Slam = 103,
    Stance = 104,
    NonRepeatable = 105,
    OtherThingUsesSkill = 106,
    Steel = 107,
    Hex = 108,
    Mark = 109,
    Aegis = 110,
    Orb = 111,
    KillNoDamageModifiers = 112,
    RandomElement = 113,
    LateConsumeCooldown = 114,
    Arcane = 115,
    FixedCastTime = 116,
    RequiresOffHandNotWeapon = 117,
    Link = 118,
    Blessing = 119,
    ZeroReservation = 120,
    DynamicCooldown = 121,
    Microtransaction = 122,
    OwnerCannotUse = 123,
    ProjectilesNumberModifiersNotApplied = 124,
    TotemsAreBallistae = 125,
    SkillGrantedBySupport = 126,
    PreventHexTransfer = 127,
    MinionsAreUndamagable = 128,
    InnateTrauma = 129,
    DualWieldRequiresDifferentTypes = 130,
    NoVolley = 131,
    Retaliation = 132,
    NeverExertable = 133,
    DisallowTriggerSupports = 134,
    ProjectileCannotReturn = 135,
    Offering = 136,
    SupportedByBane = 137,
    WandAttack = 138,
    GainsIntensity = 139,
    CreatesSentinelMinion = 140,
    SupportedByAutoExertion = 141,
}

impl SkillType {
    #[must_use]
    pub fn from_u8(v: u8) -> Option<Self> {
        // Generated from the enum above. Keep in sync.
        if v == 0 || v > 141 {
            return None;
        }
        // Safety: SkillType is repr(u8) and densely populated 1..=141 (with some
        // intentional Removed* slots). Use a match for clarity.
        Some(match v {
            1 => Self::Attack,
            2 => Self::Spell,
            3 => Self::Projectile,
            4 => Self::DualWieldOnly,
            5 => Self::Buff,
            6 => Self::Removed6,
            7 => Self::MainHandOnly,
            8 => Self::Removed8,
            9 => Self::Minion,
            10 => Self::Damage,
            11 => Self::Area,
            12 => Self::Duration,
            13 => Self::RequiresShield,
            14 => Self::ProjectileSpeed,
            15 => Self::HasReservation,
            16 => Self::ReservationBecomesCost,
            17 => Self::Trappable,
            18 => Self::Totemable,
            19 => Self::Mineable,
            20 => Self::ElementalStatus,
            21 => Self::MinionsCanExplode,
            22 => Self::Removed22,
            23 => Self::Chains,
            24 => Self::Melee,
            25 => Self::MeleeSingleTarget,
            26 => Self::Multicastable,
            27 => Self::TotemCastsAlone,
            28 => Self::Multistrikeable,
            29 => Self::CausesBurning,
            30 => Self::SummonsTotem,
            31 => Self::TotemCastsWhenNotDetached,
            32 => Self::Fire,
            33 => Self::Cold,
            34 => Self::Lightning,
            35 => Self::Triggerable,
            36 => Self::Trapped,
            37 => Self::Movement,
            38 => Self::Removed38,
            39 => Self::DamageOverTime,
            40 => Self::RemoteMined,
            41 => Self::Triggered,
            42 => Self::Vaal,
            43 => Self::Aura,
            44 => Self::Removed44,
            45 => Self::CanTargetUnusableCorpse,
            46 => Self::Removed46,
            47 => Self::RangedAttack,
            48 => Self::Removed48,
            49 => Self::Chaos,
            50 => Self::FixedSpeedProjectile,
            51 => Self::Removed51,
            52 => Self::ThresholdJewelArea,
            53 => Self::ThresholdJewelProjectile,
            54 => Self::ThresholdJewelDuration,
            55 => Self::ThresholdJewelRangedAttack,
            56 => Self::Removed56,
            57 => Self::Channel,
            58 => Self::DegenOnlySpellDamage,
            59 => Self::Removed59,
            60 => Self::InbuiltTrigger,
            61 => Self::Golem,
            62 => Self::Herald,
            63 => Self::AuraAffectsEnemies,
            64 => Self::NoRuthless,
            65 => Self::ThresholdJewelSpellDamage,
            66 => Self::Cascadable,
            67 => Self::ProjectilesFromUser,
            68 => Self::MirageArcherCanUse,
            69 => Self::ProjectileSpiral,
            70 => Self::SingleMainProjectile,
            71 => Self::MinionsPersistWhenSkillRemoved,
            72 => Self::ProjectileNumber,
            73 => Self::Warcry,
            74 => Self::Instant,
            75 => Self::Brand,
            76 => Self::DestroysCorpse,
            77 => Self::NonHitChill,
            78 => Self::ChillingArea,
            79 => Self::AppliesCurse,
            80 => Self::CanRapidFire,
            81 => Self::AuraDuration,
            82 => Self::AreaSpell,
            83 => Self::Or,
            84 => Self::And,
            85 => Self::Not,
            86 => Self::Physical,
            87 => Self::AppliesMaim,
            88 => Self::CreatesMinion,
            89 => Self::Guard,
            90 => Self::Travel,
            91 => Self::Blink,
            92 => Self::CanHaveBlessing,
            93 => Self::ProjectilesNotFromUser,
            94 => Self::AttackInPlaceIsDefault,
            95 => Self::Nova,
            96 => Self::InstantNoRepeatWhenHeld,
            97 => Self::InstantShiftAttackForLeftMouse,
            98 => Self::AuraNotOnCaster,
            99 => Self::Banner,
            100 => Self::Rain,
            101 => Self::Cooldown,
            102 => Self::ThresholdJewelChaining,
            103 => Self::Slam,
            104 => Self::Stance,
            105 => Self::NonRepeatable,
            106 => Self::OtherThingUsesSkill,
            107 => Self::Steel,
            108 => Self::Hex,
            109 => Self::Mark,
            110 => Self::Aegis,
            111 => Self::Orb,
            112 => Self::KillNoDamageModifiers,
            113 => Self::RandomElement,
            114 => Self::LateConsumeCooldown,
            115 => Self::Arcane,
            116 => Self::FixedCastTime,
            117 => Self::RequiresOffHandNotWeapon,
            118 => Self::Link,
            119 => Self::Blessing,
            120 => Self::ZeroReservation,
            121 => Self::DynamicCooldown,
            122 => Self::Microtransaction,
            123 => Self::OwnerCannotUse,
            124 => Self::ProjectilesNumberModifiersNotApplied,
            125 => Self::TotemsAreBallistae,
            126 => Self::SkillGrantedBySupport,
            127 => Self::PreventHexTransfer,
            128 => Self::MinionsAreUndamagable,
            129 => Self::InnateTrauma,
            130 => Self::DualWieldRequiresDifferentTypes,
            131 => Self::NoVolley,
            132 => Self::Retaliation,
            133 => Self::NeverExertable,
            134 => Self::DisallowTriggerSupports,
            135 => Self::ProjectileCannotReturn,
            136 => Self::Offering,
            137 => Self::SupportedByBane,
            138 => Self::WandAttack,
            139 => Self::GainsIntensity,
            140 => Self::CreatesSentinelMinion,
            141 => Self::SupportedByAutoExertion,
            _ => return None,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn keyword_flag_default_matches_when_mod_has_no_keywords() {
        // empty mod keywords always match
        assert!(KeywordFlag::matches(KeywordFlag::FIRE, KeywordFlag::empty()));
    }

    #[test]
    fn keyword_flag_default_matches_intersection() {
        assert!(KeywordFlag::matches(
            KeywordFlag::FIRE | KeywordFlag::ATTACK,
            KeywordFlag::FIRE,
        ));
        assert!(!KeywordFlag::matches(
            KeywordFlag::COLD,
            KeywordFlag::FIRE,
        ));
    }

    #[test]
    fn keyword_flag_match_all_requires_all_bits() {
        let mod_kw = KeywordFlag::FIRE | KeywordFlag::ATTACK | KeywordFlag::MATCH_ALL;
        assert!(KeywordFlag::matches(KeywordFlag::FIRE | KeywordFlag::ATTACK, mod_kw));
        assert!(!KeywordFlag::matches(KeywordFlag::FIRE, mod_kw));
    }

    #[test]
    fn skill_type_round_trip() {
        for v in 1u8..=141 {
            if let Some(st) = SkillType::from_u8(v) {
                assert_eq!(st as u8, v);
            }
        }
    }
}
