//! Sprite atlas metadata for the passive tree.
//!
//! Loaded from `data/sprites/<version>.json`, which is generated by
//! `tools/sprites_to_json.lua` against the upstream PoB
//! `src/TreeData/<version>/sprites.lua`. Each sprite category
//! (`normalActive`, `notableActive`, `keystoneActive`, `masteryInactive`,
//! ...) carries the atlas filename + a map of icon path → pixel rect.

use ahash::HashMap;
use serde::{Deserialize, Serialize};

/// Top-level sprite-set keyed by category. JSON shape:
///
/// ```text
/// {
///   "normalActive": {
///     "filename": "...",
///     "w": 962, "h": 1370,
///     "coords": { "Art/2DArt/SkillIcons/...": [x, y, w, h], ... }
///   },
///   ...
/// }
/// ```
pub type SpriteSet = HashMap<String, SpriteCategory>;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SpriteCategory {
    pub filename: String,
    pub w: u32,
    pub h: u32,
    pub coords: HashMap<String, SpriteRect>,
}

/// Pixel rect inside the atlas: [x, y, w, h]. Stored as [f32; 4] so
/// downstream code can normalize to UV without re-parsing.
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct SpriteRect(pub [f32; 4]);

impl SpriteRect {
    pub fn x(&self) -> f32 { self.0[0] }
    pub fn y(&self) -> f32 { self.0[1] }
    pub fn w(&self) -> f32 { self.0[2] }
    pub fn h(&self) -> f32 { self.0[3] }

    /// Normalised UV rect against the given atlas size: `[u, v, du, dv]`
    /// in the [0, 1] range.
    pub fn uv(&self, atlas_w: f32, atlas_h: f32) -> [f32; 4] {
        [
            self.x() / atlas_w,
            self.y() / atlas_h,
            self.w() / atlas_w,
            self.h() / atlas_h,
        ]
    }
}

/// Parse a `sprites.json` document.
pub fn load_sprites(json: &str) -> serde_json::Result<SpriteSet> {
    serde_json::from_str(json)
}
